CREATE TABLE KH_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME NVARCHAR2(5) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	MAJOR NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN KH_STUDENT.STD_NO IS '학번';
COMMENT ON COLUMN KH_STUDENT.STD_NAME IS '이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE IS '나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR IS '전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE IS '입학 날짜';

-- STD_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_STD_NO
START WITH 100
NOCACHE;

-- 샘플 데이터
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '이철수', 20, '간호학과', DEFAULT);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '김영희', 21, '사회복지학과', DEFAULT);

COMMIT;

SELECT * FROM KH_STUDENT;

SELECT STD_NO 학번, STD_NAME 이름, STD_AGE 나이, MAJOR 전공,
TO_CHAR(ENT_DATE, 'YYYY"년" MM"월" DD"일"') 입학일
FROM KH_STUDENT;

SELECT STD_NO FROM KH_STUDENT WHERE STD_NAME = '김철수';

UPDATE KH_STUDENT SET STD_NAME = '김철수'
WHERE STD_NAME = '이철수';

DELETE FROM KH_STUDENT
WHERE STD_NO = '100';